### ISSUE TITLE
Suggestion: Limit furniture per permission

### ISSUE THREAD

**Issue by Malachiel87** [Ste3et/furniture#42]
I would like to manage furniture limit by using permission, something like this
group1 = furniture.globallimit.5 = group have this permission will be able to place maximum 5 furniture
group2 = furniture.globallimit.20 = group have this permisison will be able to place maximum 20 furniture

I think is more better than using the config that will setup only one limit :)

Plotsquared is already doing it, try to see their code, it would be a nice addition to add i think

**Comment by Ste3et** [comment]
Can you test please this kind of snapshot https://dicecraft.de/furniture/download.php?plugin=FurnitureLib&build=DevBuild&version=Spigot%201.13.x&buildNummer=107 the permissions is furniture.globallimit.# you can increase the limitGlobal in the config.yml this is the search radius i implement a /furniture reload command as WIP

**Comment by Malachiel87** [comment]
Is working perfect, i tested the permission and reload and do the exact tstuff that i wanted

**Comment by Ste3et** [comment]
ok thank you for the feedback and the nice idea if you have any another nice idea please tell it me 👍

**Comment by Malachiel87** [comment]
i noticed many furniture stopped to work after your ufficial update, is normal?

**Comment by Ste3et** [comment]
The Differents between the dev build & the official build is 1 debug line, explain Pls the problems

**Comment by Malachiel87** [comment]
i noticed it also happen with the dev version, example trying to place the forniture "lampa" it will trow this
https://gist.github.com/xion87/570192f31d3283e7de0ea2c9b5713634
I am using mysql

**Comment by Ste3et** [comment]
I Have locate the error, but atm i cannot fix it. Last Monday i drive to Holland and i Comeback next week Monday, sry

**Comment by Malachiel87** [comment]
is not urgent, take your time :) <3

**Comment by Ste3et** [comment]
Thank You but iam Not in Holland to make holidays :/ i must be Work on the electrical  generator of a recyclingcenter.

**Comment by Malachiel87** [comment]
any news?

**Comment by Ste3et** [comment]
i think it is fixed can you test the newest furniturelib build ?

**Comment by xion87** [comment]
it seem no, still have report of issues that users are unable to place forniture

**Comment by Malachiel87** [comment]
Perfect now is working fine!
Another thing,  how i can use the message used "LimitAouncerMaximum" ? because it keep to use the message without the max announced

**Comment by Ste3et** [comment]
Can you please explain your question, i didn't understand that.

**Comment by Malachiel87** [comment]
i mean the message that popup when you place a forniture saying you placed 1/10 of cactus (1 of 20 total), instead saying that it saying the shorten message without the placed total forniture, and people still have issue with placing forniture also with the new release

**Comment by Ste3et** [comment]
Can you explain the placing problem, it give no changes about the placing sience last year.

**Comment by Malachiel87** [comment]
The problem is
i am using permission limiter ok?
vip 1: 10 limit forniture
vip 2: 20 limit forniture 
Sometimes is working, sometimes not, on plotsquared plots

**Comment by Malachiel87** [comment]
I got the confirmation only the people with permission limit 10 got the issue

**Comment by Malachiel87** [comment]
using luckperms
![image](https://user-images.githubusercontent.com/3611852/53688950-f4c67880-3d4b-11e9-8c46-3049167a4c0b.png)

**Comment by Malachiel87** [comment]
ok i am stupid i missed furniture.player permission for the vip_creative
